name: Makefile CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Build program
      run: |
        mkdir build
        make
      
    - name: Run tests
      run: make test
